Entrega3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('inicio.urls')),
    path('admin/', admin.site.urls),
]

inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('articulos_en_venta/', views.articulos_en_venta, name='articulos_en_venta'),
    path('iniciar_venta/', views.iniciar_venta, name='iniciar_venta'),
    path('iniciar_compra/', views.iniciar_compra, name='iniciar_compra')
]

inicio/models.py
from django.db import models

# Create your models here.

class Vender(models.Model):
    articulo = models.CharField(max_length=30)
    precio = models.IntegerField()
    fecha_de_oferta = models.DateField(null=True)
    
    
class Comprar(models.Model):
    articulo = models.CharField(max_length=30)
    precio = models.IntegerField()
    fecha_de_oferta = models.DateField(null=True)

inicio/forms.py
from django import forms

class IniciarVentaFormulario(forms.Form):
    articulo = forms.CharField(max_length=30)
    precio = forms.IntegerField()
    fecha_de_oferta = forms.DateField(required=False)
    
class BuscarArticulo(forms.Form):
    articulo = forms.CharField(max_length=30, required=False)
    
class IniciarCompraFormulario(forms.Form):
    articulo = forms.CharField(max_length=30)
    precio = forms.IntegerField()
    fecha_de_oferta = forms.DateField(required=False)

inicio/views.py
from django.shortcuts import render, redirect
from inicio.forms import IniciarVentaFormulario, IniciarCompraFormulario, BuscarArticulo
from inicio.models import Vender, Comprar


# Create your views here.

def inicio(request):
    return render(request, 'inicio/inicio.html')

def articulos_en_venta(request):
    
    formulario = BuscarArticulo(request.GET)
    if formulario.is_valid():
        articulo_a_buscar = formulario.cleaned_data['articulo']
        listado_de_articulos = Vender.objects.filter(articulo__icontains=articulo_a_buscar)
   
    formulario = BuscarArticulo()    
    return render(request, 'inicio/articulos_en_venta.html', {'formulario': formulario, 'articulos':listado_de_articulos})


def iniciar_venta(request):
    mensaje = ''
    if request.method == 'POST':
        forumulario = IniciarVentaFormulario(request.POST)
        if forumulario.is_valid():
            info = forumulario.cleaned_data
            venta = Vender(articulo=info['articulo'],precio=info['precio'],fecha_de_oferta=info['fecha_de_oferta'])
            venta.save()
            return redirect('inicio:articulos_en_venta')
        else:
            return render(request, 'inicio/iniciar_venta.html', {'formulario': forumulario})
    forumulario = IniciarVentaFormulario()
    return render(request, 'inicio/iniciar_venta.html', {'formulario': forumulario, 'mensaje':mensaje})


   
    
def iniciar_compra(request):
    mensaje = ''
    if request.method == 'POST':
        forumulario = IniciarCompraFormulario(request.POST)
        if forumulario.is_valid():
            info = forumulario.cleaned_data
            compra = Comprar(articulo=info['articulo'],precio=info['precio'],fecha_de_oferta=info['fecha_de_oferta'])
            compra.save()
            mensaje = f'Se realizo la compra de {compra.articulo} al valor de USD {compra.precio}'            
        else:
            return render(request, 'inicio/iniciar_compra.html', {'formulario': forumulario})
    forumulario = IniciarCompraFormulario()
    return render(request, 'inicio/iniciar_compra.html', {'formulario': forumulario, 'mensaje':mensaje})
    
    
    

inicio/templates/inicio/articulos_en_venta.html
{% extends 'base.html' %}

{% block title_head %}
<title>Articulos en venta </title>
{% endblock title_head %}

{% block h1_header %}
Articulos en venta 
{% endblock h1_header %}

{% block contenido %}
<button>
<a class="navbar-brand" href={% url 'inicio:iniciar_venta' %}>Vender</a>
</button>
<form action="" method="get">
    {% csrf_token %}
        {{formulario}}    
    <button>Buscar</button>
</form>
{% if articulos %}
{% for articulo in articulos %}
<li> Articulo: {{articulo.articulo}} - Precio: {{articulo.precio}} </li>
{% endfor %}
{% else %}
<p>EL articulo buscado no se encuentra en venta</p>
{% endif %}

{% endblock contenido %}

inicio/templates/inicio/iniciar_compra.html
{% extends 'base.html' %}

{% block title_head %}
<title>Comprar</title>
{% endblock title_head %}

{% block h1_header %}
Iniciar compra 
{% endblock h1_header %}


{% block contenido %}
<p> {{mensaje}} </p>

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Comprar</button>
</form>

{% endblock contenido %}



{% comment %} {% block contenido %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Comprar</button>
</form>

{% endblock contenido %}

 {% endcomment %}

inicio/templates/inicio/iniciar_venta.html
{% extends 'base.html' %}

{% block title_head %}
<title>Vender</title>
{% endblock title_head %}

{% block h1_header %}
Iniciar venta
{% endblock h1_header %}


{% block contenido %}
<p> {{mensaje}} </p>

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Vender</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/inicio.html
{% extends 'base.html' %}

{% block title_head %}
<title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
Bienvenidos a mi pagina 
{% endblock h1_header %}


{% block contenido %}
<p>      En esta pagina podran:</p>
<p>         - ver distintos articulos en venta,</p>
<p>         - publicar nuevos, </p>
<p>         - y realizar las compras que deseen</p>

<p>         Disfruten su estadia</p>
{% endblock contenido %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Landing Page - Start Bootstrap Theme</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
                <a class="navbar-brand" href={% url 'inicio:articulos_en_venta' %}>Listado de articulos en venta</a>
                <a class="navbar-brand" href={% url 'inicio:iniciar_compra' %}>Comprar</a>
                {% comment %} <a class="btn btn-primary" href={% url 'inicio:iniciar_compra' %}>Iniciar compra</a> {% endcomment %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            
                            <h1 class="mb-5">
                                {% block h1_header %}
                                {% endblock h1_header %}
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% block contenido %}
        {% endblock contenido %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'js/scripts.js' %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>